#!/bin/bash

DIR="/home/$USER/data"

if [ ! -d $DIR ]; then
      mkdir -p "/home/$USER/data"
fi

if [ ! "$1" ]; then
      echo "container id or container name required"
      exit 1
fi

if [ ! "$2" ]; then
      echo "Backup image name required"
      exit 1
fi

#CONTAINERS=$(echo $1 | tr "/" " ")
IMAGE_NAME=${2,,}; #image name must be lower case

sudo docker rmi $IMAGE_NAME
echo "docker backup starting...."
sudo docker commit -p $1 $IMAGE_NAME
echo "compressing image $1 into tar file"
sudo docker save -o ~/data/backupImage.tar $IMAGE_NAME
echo "uploading image tar file into aws bucket"
sudo pipenv run python awspyupload.py -filePath ~/data/backupImage.tar -fileName $IMAGE_NAME ; CODE=$?;if [ $CODE != 0 ];then echo "python script exit with code $CODE"; exit 1; fi
echo "docker image tar file upload completed"
echo "...................................................."
echo "removing backup images from system"
sudo docker rmi $IMAGE_NAME
echo "removing backup file from system"
sudo rm ~/data/backupImage.tar
echo "backup process completed for $1"
